### ISSUE TITLE
jslint mess up vim input in terminal

### ISSUE THREAD

**Issue by lxyu** [hallettj/jslint.vim#32] opened 2011-10-26 16:47 UTC
jslint works fine with macvim, but in terminal, things go wrong.
1. under vim insert mode, chars I didn't input will somehow be inputed.
2. under vim normal mode, some words will be replace when cursor move over it, but only change in display, not file change. refresh by page down and up will get these changed word recover.

**Comment by jordwalke** [comment] 2011-10-27 19:52
Experiencing the same problems with iTerm - yet MacVim works fine.

**Comment by DanielBaulig** [comment] 2012-03-14 14:34
I experience the same problem in rxvt-unicode under Linux.
It is not reproduceable reliably, however, it seems to happen sometimes when changing from insert mode to normal mode, eg:

```
<i>function f() { return 0; }<ESC>:w
```

might yield to

```
function f() { return 0; w
```

beeing displayed. However, the correct text was written to the file.

**Comment by nchase** [comment] 2012-04-03 23:35
I have a similar issue too...

**Comment by DanielBaulig** [comment] 2012-04-04 07:23
It seems like this issue is related to the CPU processing power. If I have my laptop plugged in to power and the CPU at full speed, it is very unlikely that this happens. If I have my laptop unplugged and the CPU clock reduced to save power, this happens much more often.

**Comment by nchase** [comment] 2012-04-04 07:38
Check your other plugins? I just did some housekeeping in my `.vim` directory and I don't seem to be getting this any more. 

Unfortunately I deleted a bunch of things all at once so I don't know what the problem file truly was.

**Comment by nchase** [comment] 2012-04-04 11:43
OK - do any of you use buftabs.vim by any chance?

**Comment by evgenyneu** [comment] 2012-04-07 08:51
I noticed those random characted appearing in VIM, at the end of the lines. 'w' in most cases. It is VERY annoying and makes me disable this plugin when I do not need it.

The characters disappear when refreshing the screen (Ctrl-L).

I have tested it in clean VIM install with nothing in `~/.vim` directory except jslint plugin. Tested in Ubuntu 11.10, VIM 7.3.154 compiled from sources with defaults. There is only ftplugin/javascript in ~/.vim folder. ~/.vimrc has only "filetype plugin on"

![VIM glitch exaimple](http://dl.dropbox.com/u/11143285/misc/2012/lslint-vim-artifact.png)

To recreate:

1) Edit a new file with VIM: `vim new.js`
2) Enter insert mode and type:
var a = 2,
    b = 3;

3) Then click `Esc` and `:w` to save it.

4) 'w' will appear instead of ';' after '3'.

I've noticed that the bug is random and appear more often when you type fast.

**Comment by janewilkin** [comment] 2012-04-17 23:24
I noticed this too.  I have a habit that whenever I save, I automatically toggle up and down a line with the j & k keys.  Doing this when using jslint results in j being written to the line.  Here's the sequence of keys, do this on any line:
1. i
2. ESC
3. j
4. k

this will result in j being written to the line. 

I am doing this is OSX Terminal.

Here's my vimrc:  https://gist.github.com/2409842

**Comment by DanielBaulig** [comment] 2012-04-19 19:47
I also tesed it with only jslint active and it still happens.

**Comment by tingham** [comment] 2012-07-07 01:06
Not really a fix but CTRL+L will repaint your display and fix those chars. I'm pretty sure it's just the Mac. Mine does it with and without the jslint plugin.

**Comment by evgenyneu** [comment] 2012-07-07 05:05
@tingham, I had the same issue on Ubuntu as well. In my case it is completely fixed by disabling jslint plugin.

**Comment by tingham** [comment] 2012-07-07 07:28
@evgenyneu Not really a fix though is it? Would love to have the jslint back working inline.

**Comment by evgenyneu** [comment] 2012-07-07 07:39
@tingham, right, I did not suggest a fix. What I meant is that the issue is `probably` caused by jslint plugin for my case, because the glitch disappears when I disable it. It is possible though that the issue is not in jslint but jslint just helps to reveal it (pure speculation).

**Comment by bbinet** [comment] 2012-09-13 14:24
Same problem here on ubuntu. Anybody found a fix for this issue?

**Comment by louisbranch** [comment] 2012-09-17 01:24
Got the same problem on Arch Linux using Vim 7.3

**Comment by francoisjacques** [comment] 2013-05-21 16:26
Same problem can be reproed on vim under cygwin (console mode). Thanks for the Ctrl-L tip tingham.

I also found that js.exe gets invoked anytime I move the cursor around which is a little bit to much. I'm fine with js.exe being invoked after a document modification, save and upon the opening of the document. But not on cursor movement. 

I'm using vim 7.3 with patcheset 1-692. Built locally with cygwin gcc toolset.

**Comment by gsavovski** [comment] 2013-12-14 22:12
Anybody figured this out? Same issue on ubuntu 12.10 on Vim 7.3.
I don't won't to go the sublime route :-(

**Comment by boompig** [comment] 2014-06-25 18:13
Same issue on Mac OS 10.9.3, Vim 7.3 which ships with Mac.

**Comment by tsterker** [comment] 2014-06-26 15:26
I had the same issues with

> - Ubuntu 13.04
> - Vim 7.4

And unfortunately it is so annoying that I can't bear to use this awesome plugin :/

**Comment by acoover** [comment] 2015-11-13 16:19
This is also occurring for me. I just installed https://github.com/wookiehangover/jshint.vim and am seeing this issue.
- VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Aug 22 2015 15:38:58)
- iTerm 2 Build 2.1.4
- OSX El Capitan 10.11.1

**Closed as completed** 2016-09-19 10:12 UTC
